# Test generated by ChatGPT

import socket
import time

SERVER_IP = "127.0.0.1"   # Must match current_ip in your main program
SERVER_PORT = 7501        # Must match receive_port in your main program
LISTEN_PORT = 7500        # Must match send_port in your main program

# --- Setup UDP sockets ---

# Socket to send to your main program
send_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

# Socket to receive from your main program (optional, to test Send_Loop)
recv_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
recv_sock.bind(("0.0.0.0", LISTEN_PORT))
recv_sock.settimeout(1.0)

print(f"[CLIENT] Started test client")
print(f"[CLIENT] Will send messages to {SERVER_IP}:{SERVER_PORT}")
print(f"[CLIENT] Will listen for replies on port {LISTEN_PORT}")

# --- Send a few test messages ---
for i in range(5):
    message = f"test_message_{i}"
    print(f"[CLIENT] Sending: {message}")
    send_sock.sendto(message.encode(), (SERVER_IP, SERVER_PORT))
    time.sleep(0.5)

# --- Listen for replies from server for a few seconds ---
print("[CLIENT] Waiting for any messages from server...")
start = time.time()
while time.time() - start < 5:
    try:
        data, addr = recv_sock.recvfrom(2048)
        print(f"[CLIENT] Got message from {addr}: {data.decode()}")
    except socket.timeout:
        pass

print("[CLIENT] Test finished. Closing sockets.")
send_sock.close()
recv_sock.close()
